# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='typ',
            field=models.CharField(default=234, max_length=100),
            preserve_default=False,
        ),
    ]
