# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20160406_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offert',
            field=models.BooleanField(default=0),
        ),
    ]
